api_platform:
    title: Pawnity API
    version: 0.2.33
    mapping:
        paths: ['%kernel.project_dir%/src']
    defaults:
        normalization_context: { groups: ['read'] }
        denormalization_context: { groups: ['write'] }
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']