nelmio_api_doc:
    documentation:
        info:
            title: 'API Documentation'
            description: 'This is the API documentation for the EventEco project.'
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    html_config:
        swagger_ui_config:
            display_operation_id: true
            display_request_duration: true
