doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
        types:
            statusEvent: App\Infrastructure\Persistence\Doctrine\Enums\StatusEventEnumType
            statusSubEvents: App\Infrastructure\Persistence\Doctrine\Enums\StatusSubEventsEnumType
            orderstatusenum: App\Infrastructure\Persistence\Doctrine\Enums\OrderStatusEnumType
            orderLineStatusEnum: App\Infrastructure\Persistence\Doctrine\Enums\OrderLineStatusEnumType
            ticketUnitStatusEnum: App\Infrastructure\Persistence\Doctrine\Enums\TicketUnitStatusEnumType
            ticketComplementsStatusEnum: App\Infrastructure\Persistence\Doctrine\Enums\TicketComplementsStatusEnumType
            notificationStatusEnum: App\Infrastructure\Persistence\Doctrine\Enums\NotificationStatusEnumType
            incidentsStatusEnum: App\Infrastructure\Persistence\Doctrine\Enums\IncidentsStatusEnumType
            petGenderEnum: App\Infrastructure\Persistence\Doctrine\Enums\PetGenderEnumType
            petStatusEnum: App\Infrastructure\Persistence\Doctrine\Enums\PetStatusEnumType
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        class_metadata_factory_name: IS\Bumbu\Doctrine\CustomClassMetadataFactory
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        controller_resolver:
            auto_mapping: false
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Organizer/Domain/Entity'
                prefix: 'App\Organizer\Domain\Entity'  # Aquí está la corrección
                alias: App
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
